### ISSUE TITLE
l2_norm F_label

### ISSUE THREAD

**Issue by CuongNN218** [OpenGVLab/Multitask-Model-Selector#1]
Dear authors,

Thanks for your great work and congrats your publication. After reading your paper and the code, I see a mismatch between the description in the paper and your implementation. In the paper, you said that "the label embedding z is obtained by l2 normalization" but in your implementation, you feed the no_norm embedding to the metric calculators as in line [85](https://github.com/OpenGVLab/Multitask-Model-Selector/blob/153a4e23719f69cb4e5c26db565d916605ddfe04/evaluate_metric_caption_cpu.py#L85). I wonder that do we have to normalize the F_label for a better calculation. 

Feel free to correct me if I misunderstoood. 

Best,

**Comment by FanqingM** [comment]
Hi，After standardizing both the label embedding vectors and feature vectors, we perform calculations as shown in the EMMS function in the metric.py file.

**Comment by FanqingM** [comment]
In our methods, we first standardlize both the label embedding vectors and feature vectors then do EMMS, which can be found in EMMS function in the metric.py.
Here, We can use different method to standardlize, and in this version, we use Z-score normalization as shown in EMMS function in the metric.py, which can get better results.
But It is not important in our methods, just do standardlization then do EMMS.
Feel free to call me if you have any questions.

**Comment by FanqingM** [comment]
We do standardlization just because regression method usually need to do this first.

**Comment by kevinvlowell** [comment]
Is feature normalization handled within the functions for all described methods (i.e. SFDA, TransRate, etc)? Or should feature matrices be normalized prior to calculation of these other scores?

**Comment by FanqingM** [comment]
We use normalization here because we are modeling this as a regression problem, and regression problems often require prior normalization. I believe this depends on the way the problem is modeled, and specific papers can be referenced for this. I think this is not crucial, as it appears in our case as a supporting measure for the regression method.
