### ISSUE TITLE
Mismatch output dimension from foundation models

### ISSUE THREAD

**Issue by MoeinSorkhei** [OpenGVLab/Multitask-Model-Selector#2]
Hello @FanqingM , thanks for your nice work.
When I run code to get embeddings from `clip`, `bert`, and `gpt-2`, I get an error in during evaluation [here](https://github.com/OpenGVLab/Multitask-Model-Selector/blob/153a4e23719f69cb4e5c26db565d916605ddfe04/evaluate_metric_cls_cpu_ViT.py#L183), stating that "there is a mismatch between the outputs of foundation models", and so they outputs cannot be stacked.
Specifically, outputs from Clip and Bert have dimension `[N, 1024]`, while gpt-2 has `[N, 1280]` so they cannot be stacked.

Do you have any suggestion on how to resolve this?

**Comment by MoeinSorkhei** [comment]
Does it suffice if only the encodings from 1 or 2 of the foundation models are used?

**Comment by FanqingM** [comment]
Sorry, It should use gpt2-medium, And it dim is 1024.
For our method, we must use foundation models that their embedding dim is same.
